import Foundation
import XCTest

/*
 Find the Difference
 
 Given two strings s and t which consist of only lowercase letters.

 String t is generated by random shuffling string s and then add one more letter at a random position.

 Find the letter that was added in t.
 */

class Solution {
    func findTheDifference(_ s: String, _ t: String) -> Character {
        var hashTable = [Character:Int]()
        for char in s {
            hashTable[char, default: 0] -= 1
        }
        for char in t {
            hashTable[char, default: 0] += 1
        }
        return hashTable.first(where: { $0.value == 1 })?.key ?? " "
    }
}

class Solution2 {
    func findTheDifference(_ s: String, _ t: String) -> Character {
        var sum: UInt32 = 0
        sum = s.unicodeScalars.reduce(into: sum) { $0 ^= $1.value }
        sum = t.unicodeScalars.reduce(into: sum) { $0 ^= $1.value }
        return Character(UnicodeScalar(sum)!)
    }
}

class SolutionTests: XCTestCase {
    
    var solution = Solution2()
    
    func testExampleOne() {
        XCTAssertEqual(solution.findTheDifference("abcd", "abcde"), "e")
    }
    
}

SolutionTests.defaultTestSuite.run()

